### ISSUE TITLE
easily enable/disable Oauth for all ingresses

### ISSUE THREAD

**Issue by jbianquetti-nami** [bitnami/kube-prod-runtime#336]
Currently, we’re using  `oauth2_proxy: null` on kubeprod-manifests. Would be nice if we can completely remove a feature when running kubeprod using a flag.

**Comment by anguslees** [comment]
No :)

We don't want to expose customisations as flags, because that many flags are going to be horrible to use, limited in what they can describe (flat key=value only), and a lot more work for us to maintain, document, and test.

The customisation mechanism we've designed is to just use `oauth2_proxy: null` in a `kubeprod-manifest.jsonnet` "override" - exactly as you're currently doing.  The workflow preserves these modifications across upgrades, and allows you to share/reuse modifications if they become complex.  If this mechanism doesn't work for you, I'd be _very_ interested in learning more about the issues you've encountered.

In particular, if we make it a flag, we're declaring that **we** (BKPR devs) support (and test, etc) all possible combinations of the flags we offer, and that software deployed onto BKPR needs to assume that any combination of those flag may/may not have been used (eg: can't assume that an OAuth2 solution exists).  The combinations here explode _very_ quickly.

If we make it an override, however, then we're declaring that the **individual deployer** is responsible for verifying that their specific customisation makes sense in their particular situation (eg: a private internal cluster may not want OAuth2, and will also be aware and prepared to customise future applications that default to using OAuth2).

**Comment by jjo** [comment]
Ok :)

For this particular case (ingresses oauth), note that with the switch to ACME DNS01 it would become feasible/reasonable for users to deploy BKPR on environments without public LBs reachability, thus having `oauth2-proxy` as optional a potentially more common use case.

**Comment by anguslees** [comment]
@jjo: I agree 100%, and we should switch BKPR to use DNS-01 challenges (#304).  In particular DNS challenges allow the ingress stack - including oauth2 - to work on private/internal loadbalancers (with only DNS entries publicly exposed).

Thanks for following up.  Assuming DNS-01 ACME challenges would deal with the underlying motivation here, I'm closing this in favour of #304.
