### ISSUE TITLE
GKE - verify service account has permissions

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#384]
When re-installing a few times I was getting `403 Forbidden` in the logs of external-dns. This was because the service account, after exploration afterwards, appeared to be empty. 

```bash
gcloud iam service-accounts get-iam-policy \
    test-external-dns@myproj-123456.iam.gserviceaccount.com@my-project- 
    123.iam.gserviceaccount.com

etag: ACAB
```

It's working now (I had been deleting the service account and the kubeprod-autogen) although I can't spot exactly what was going wrong :-)

At any rate one possible improvement in the behaviour would be to:

On every install/upgrade
* Delete the existing `external-dns` secret if it's there
* Create a new key and secret
* Verify the key works by using :

```bash
gcloud auth activate $SERVICE_ACCOUNT
gcloud dns managed-zones list```

**Comment by anguslees** [comment]
Your external-dns issue is probably a duplicate of #64.  I've been caught by this before too and it's very confusing to debug. I agree we should add a workaround by recreating the Secret (and restarting the external-dns pods).  I suggest we followup that action item in #64.

Verifying the existing service accounts is a good suggestion, and it's easy enough to do.  I _don't_ want to make it fatal however, since "just use the value I gave you" is an important feature for complex enterprise cases where the auto-installer is insufficient.  A "this failed a simple verification test" warning seems like an excellent improvement though.

**Comment by EamonKeane** [comment]
thanks @anguslees , I'll close now and follow in 64.
