### ISSUE TITLE
Best way to annotate ingresses so that the yaml can be used with different clusters?

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/kube-prod-runtime#389]
Type: Question

I have two different Kubernetes clusters that use different DNS zones. For the purposes of this question, let's call them "dev.site" and "production.com"

I'd like to create a yaml that deploys an externally accessible service to either cluster. This is hard to do today because the ingress annotations require the fully-qualified dns name "myservice.dev.site" and "myservice.production.com" 

I would like to avoid using sed/helm/kubecfg for such a simple-case. Any ideas?

**Comment by falfaro** [comment]
Let me see if I understand your point here: you would like to use the same Jsonnet manifest for deploying to two different Kubernetes clusters, A and B. In cluster A, BKPR was installed to use DNS zone prod.exmaple.com and in B, BKPR was installed to use DNS zone dev.example.com. Your Jsonnert manifest has an Ingress resource that you would like to be named like "web" and then qualified with the correct DNS zone depending on which cluster you deploy.

When you deploy your manifest in cluster A, your Ingress will be accessible as web.prod.example.com. If you deploy that same manifest in cluster B, your Ingress will be accessible as web.dev.example.com.

Is this what you mean?

**Comment by nomisbeme** [comment]
Yes.

**Comment by arapulido** [comment]
This is the main purpose of using jsonnet. As far as I know, there is no other way other than templating.

What you should do is to have a common `application.jsonnet`, and then have a `dev.jsonnet` and `prod.jsonnet` (for example) with just the extensions you need (`dev.jsonnet` and `prod.jsonnet` should be very small, as they will just contain the additions to the common one.

You can see examples on how to do this in this examples repo: https://github.com/bitnami-labs/kube-manifests

As you can see, there is a [common folder](https://github.com/bitnami-labs/kube-manifests/tree/master/common) with the generic applications and folders with the extended manifests per environment (for example for the [dev environment](https://github.com/bitnami-labs/kube-manifests/tree/master/one.k8s.dev.bitnami.net)).

There is also a CNCF webinar on how to do this: https://www.cncf.io/community/webinars/writing-less-yaml-using-jsonnet-and-kubecfg-to-manage-kubernetes-resources/

Let me know if that answers your question.

**Comment by falfaro** [comment]
I see that the main pain point here is that Ingress resources require a `host` property, and this propery must equal the fully-qualified domain name (FQDN DNS name, e.g. `foo.example.com`) under which your Ingress can be reached over the Internet.

One potential solution for this "problem" that is agnostic to whether you want to use `kubectl`, jsonnet, or any other language would be allow Ingress resources to have a non-FQDN name (e.g. `foo`) and have BKPR append the DNS suffix that was used during installation (e.g. `example.com`) so that in the end the Ingress resource can be reached via `foo.example.com`.

Kubernetes supports mutating webhook admission controllers, and BKPR could add one to the Kubernetes cluster to detect those Ingress resources that do not specify an FQDN. For these Ingress resources, this admission controller can patch the `host` attribute to append the DNS suffix used by BKPR.

**Comment by falfaro** [comment]
Oh, and even better: this admission controller could even support Ingress resources without the `host` attribute. In this case, the `host` attribute is patched to be the combination of the Ingress resource name plus the DNS suffix used when installing BKPR.

**Comment by arapulido** [comment]
@falfaro I think this are two different things. The question @nomisbeme is asking, and a potential improvement to make this easier. Can you open a new issue with your feature improvement suggestion, rather than mixing it here, please? That way we can close the conversation, and continue the one about the new feature in a specific issue.

**Comment by nomisbeme** [comment]
This response: https://github.com/bitnami/kube-prod-runtime/issues/389#issuecomment-466953066 answers my question directly, thank you @arapulido.

@falfaro Please link to the feature request here if you create one. I'd be interested in following to see if this is a common need.

At least one other person might be interested in this type of capability: https://github.com/kubernetes/kubernetes/issues/50003

**Comment by falfaro** [comment]
@nomisbeme see https://github.com/bitnami/kube-prod-runtime/issues/412 re: the feature request :-)
