### ISSUE TITLE
ksonnet deprecation

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#390]
Just wondering if VMWare's decision to deprecate ksonnet has any impact on `kube-prod-runtime` with `kubecfg`? It seems like it's fairly stable and most of the work done by `Bitnami` so expect it's ok just needs to be moved to new repo.

**Comment by arapulido** [comment]
Hello @EamonKeane. No, it shouldn't. Although `kubecfg` is currently under the `ksonnet` it has been a while since most of `kubecfg` maintainers are from Bitnami. We plan to move `kubecfg` repository to a different org soon, and we plan to continue maintaining it the same way that we have been doing until now. I hope that clarifies a bit
