### ISSUE TITLE
Optional Ingress choice.

### ISSUE THREAD

**Issue by Elexy** [bitnami/kube-prod-runtime#474]
I'd like to inquire if it's possible to offer users a choice between ingress controllers. Would that fit in the project's goals?

We use traefik, for it's reduced footprint (mem/cpu) and some configuration advantages. Others could be supported as well, though.

If you're interested, I might be able to get my company to sponsor the work.

**Comment by falfaro** [comment]
In any case, nothing prevents you from running multiple Ingress controllers in Kubernetes, but before we can take the decision on supporting more Ingress controllers could you provide a little bit more background? We are interested not just in reduced memory footprint, but what configuration advantages are those.

**Comment by Elexy** [comment]
@falfaro Thanks for your consideration. 
To satisfy some InfoSec requirements  we needed to remove the "server" header. While this is possible with a custom compiled Nginx Image, Traefik (for example) is able to just turn it off.

**Comment by falfaro** [comment]
And this https://www.getpagespeed.com/server-setup/nginx/how-to-remove-the-server-header-in-nginx doesn't suit you, right?

**Comment by Elexy** [comment]
That's what we thought as well, but InfoSec did not want to expose that the server was `nginx` at all.
This setting just removes the version.

**Comment by falfaro** [comment]
At the moment we don't have the development bandwidth to support Traefik but you can run it side-by-side with NGINX and annotate your Ingress resources with an annotation that "hints" Kubernetes into using Traefik instead of NGINX.

Something like this:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: your-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
```

**Comment by anguslees** [comment]
More generally, we're trying to keep the "official BKPR" as a "known quantity" that people can reasonably test against without it becoming just another soup of possible combinations.  At the same time, we want to make it easy for end-users to customise (because matching local requirements is important), with the implied bargain that now the responsibility for testing their customisation and any downstream implications is on the end-user.

So: As a project, we should support one-and-only-one Ingress implementation in each BKPR release, and at the same time make it easy to replace that choice locally.

Eg: if you have a jsonnet overlay that switches out the ingress implementation for traefik, that would be an awesome thing to share and redistribute in a 'contrib' directory or similar, so that other people can benefit from your work (and collaborate on it).

Separately: I fully expect that BKPR (project-wide) will migrate off nginx and onto something "more modern" like traefik or contour at some point.  When this happens, it would be part of a new release, and clearly called out in the release notes since it will likely affect anyone using Ingress annotations (the k8s Ingress abstraction is extremely leaky, as we all know).

---

So @Elexy, which direction would you like to take this specific GitHub issue?
1. Ensure that you can run traefik as a separate `ingress.class` alongside BKPR's unmodified nginx install?
    (I think/hope this already works?)
2. Develop a customisation overlay that switches BKPR's nginx over to traefik, and publish that somewhere?
3. Switch BKPR's default from nginx to traefik?

All sound good to me, obviously with different expectations of effort and timeline.  Note that the jsonnet part of (2) is going to be a requirement for (3) anyway.

**Comment by Elexy** [comment]
@anguslees I think #2 and #3 are a good direction. However, for our use case we want to leverage more managed cloud services for things like `logging` and `metrics`. 
As such we're developing a more bespoke set of supporting components to leverage for instance the AWS ALB and Azure monitor. 
In short our needs and intentions seem to be quite a ways away from BKPR's.
