### ISSUE TITLE
Is it possible for kube prod to dump the YAML it has generated?

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#537]
I would like to apply the various components selectively or with modifications of my own.

**Comment by jbianquetti-nami** [comment]
You can tweak the file `kubeprod-manifest.jsonnet` to include or mute all stuff wanted. See https://github.com/bitnami/kube-prod-runtime/blob/master/docs/components.md

It's also possible to dump raw manifest. Take a look at:

```
$ kubeprod  install {cloud-provider}  --only-generate
```

But personally I would recommend:

```
$ kubecfg  -J ./lib show /path/to/kubeprod-manifest.jsonnet
```

**Comment by anguslees** [comment]
What jbianquetti said :)

BKPR is designed to be highly customisable, by adding your desired modifications to `kubeprod-manifest.jsonnet`.

See https://github.com/bitnami/kube-prod-runtime/issues/320#issuecomment-459228512 for an example of the sorts of things you can do.  If you are new to jsonnet, I recommend you skim over the short/easy [tutorial](https://jsonnet.org/learning/tutorial.html) before diving in.

Also as recommended above, I suggest using [kubecfg](https://github.com/bitnami/kubecfg) rather than running the `kubeprod install` command repeatedly.  The latter will work, but kubecfg offers additional features to help you debug the jsonnet you are developing (like `kubecfg show`, `kubecfg diff`, etc).

Please reopen if you have further questions.
