### ISSUE TITLE
external-dns doesn't reread updated token secret

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#64]
Needs an explicit restart (kill the pod) to pick up the new (AKS) secret.  We need to add a config-reloader sidecar, hash the secret name, fix the code, etc.

**Comment by arapulido** [comment]
@anguslees is this still relevant?

**Comment by falfaro** [comment]
I think this is still relevant. IIRC, the problem is that External DNS only supports reloading its configuration via the SIGHUP signal and `configmap-reload` requires shared PID namespaces support (Kubernetes > 1.10) enabled.

Something like https://github.com/stakater/Reloader could help because it forces a rolling update on pods that depend on a ConfigMap.

**Comment by anguslees** [comment]
Yes, still relevant.

I think the stakater/Reloader solution is very heavy-weight, and would prefer some other approach.  But we need something here.   I don't think we need to fix this for 1.0 however.

**Comment by falfaro** [comment]
We should open a bug upstream to have a watch for ConfigMap implemented in External DNS.

**Comment by anguslees** [comment]
Opened upstream bug https://github.com/kubernetes-incubator/external-dns/issues/852
